// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zzgaenibekmdbtiqbkut.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6Z2FlbmliZWttZGJ0aXFia3V0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNjY1NDcsImV4cCI6MjA1OTg0MjU0N30.aVjhqr2hITwzCm7HvzUGFqkLrYNw-K89v40abeUIsY8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);